/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_estructuras_final.interfaz;

import proyecto_estructuras_final.logica.Control;

/**
 *
 * @author 50688
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    Control myControl;

    public MenuAdmin(Control myControl) {
        initComponents();
        this.Comidasjbtn.setVisible(false);
        this.Bebidasjbtn.setVisible(false);
        this.Postresjbtn.setVisible(false);
        this.Comidasjlist.setVisible(false);
        this.Comidasjsp.setVisible(false);
        this.Refrescarjbtn.setVisible(false);
        this.Modificarjbtn.setVisible(false);
        this.myControl = myControl;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Refrescarjbtn = new javax.swing.JButton();
        Comidasjsp = new javax.swing.JScrollPane();
        Comidasjlist = new javax.swing.JList<>();
        Modificarjbtn = new javax.swing.JButton();
        Menujbtn = new javax.swing.JButton();
        Postresjbtn = new javax.swing.JButton();
        Bebidasjbtn = new javax.swing.JButton();
        Comidasjbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Refrescarjbtn.setText("Aplicar Cambio");
        Refrescarjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescarjbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Refrescarjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        Comidasjlist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comidasjlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Comidasjsp.setViewportView(Comidasjlist);

        jPanel1.add(Comidasjsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 410, -1));

        Modificarjbtn.setText("Modificar Articulo");
        Modificarjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarjbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Modificarjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        Menujbtn.setText("Visualizar Menu");
        Menujbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenujbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Menujbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        Postresjbtn.setText("Menu Postres");
        Postresjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostresjbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Postresjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        Bebidasjbtn.setText("Menu Bebidas");
        Bebidasjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BebidasjbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Bebidasjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        Comidasjbtn.setText("Menu Comidas");
        Comidasjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidasjbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Comidasjbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_estructuras_final/Imagenes/MenuAdminn.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComidasjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidasjbtnActionPerformed
        // TODO add your handling code here:
        String[] elementosLista;
        elementosLista = this.myControl.obtenerNombres(1);
        this.Comidasjlist.setVisible(true);
        this.Comidasjsp.setVisible(true);
        Comidasjlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"1."+elementosLista[0], "2."+elementosLista[1], "3."+elementosLista[2],"4."+elementosLista[3],"5."+elementosLista[4]};
            public int getSize() {
                return strings.length;
            }
            public String getElementAt(int i) {
                return strings[i];
            }
        });
        this.Modificarjbtn.setVisible(true);
        this.Refrescarjbtn.setVisible(true);
        this.Refrescarjbtn.setEnabled(false);
    }//GEN-LAST:event_ComidasjbtnActionPerformed

    private void MenujbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenujbtnActionPerformed
        // TODO add your handling code here:
        this.Menujbtn.setVisible(false);
        this.Comidasjbtn.setVisible(true);
        this.Bebidasjbtn.setVisible(true);
        this.Postresjbtn.setVisible(true);
    }//GEN-LAST:event_MenujbtnActionPerformed

    private void BebidasjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BebidasjbtnActionPerformed
        // TODO add your handling code here:
        String[] elementosLista;
        elementosLista = this.myControl.obtenerNombres(2);
        this.Comidasjlist.setVisible(true);
        this.Comidasjsp.setVisible(true);
        Comidasjlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"1."+elementosLista[0], "2."+elementosLista[1], "3."+elementosLista[2], "4."+elementosLista[3], "5."+elementosLista[4]};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        this.Modificarjbtn.setVisible(true);
        this.Refrescarjbtn.setVisible(true);
        this.Refrescarjbtn.setEnabled(false);
    }//GEN-LAST:event_BebidasjbtnActionPerformed

    private void PostresjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostresjbtnActionPerformed
        // TODO add your handling code here:
        String[] elementosLista;
        elementosLista = this.myControl.obtenerNombres(3);
        this.Comidasjlist.setVisible(true);
        this.Comidasjsp.setVisible(true);
        Comidasjlist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"1."+elementosLista[0], "2."+elementosLista[1], "3."+elementosLista[2], "4."+elementosLista[3],"5."+elementosLista[4]};
            public int getSize() {
                return strings.length;
            }
            public String getElementAt(int i) {
                return strings[i];
            }
        });
        this.Modificarjbtn.setVisible(true);
        this.Refrescarjbtn.setVisible(true);
        this.Refrescarjbtn.setEnabled(false);
    }//GEN-LAST:event_PostresjbtnActionPerformed

    private void ModificarjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarjbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarjbtnActionPerformed

    private void RefrescarjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescarjbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefrescarjbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Control myControl = new Control();
                new MenuAdmin( myControl).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bebidasjbtn;
    private javax.swing.JButton Comidasjbtn;
    private javax.swing.JList<String> Comidasjlist;
    private javax.swing.JScrollPane Comidasjsp;
    private javax.swing.JButton Menujbtn;
    private javax.swing.JButton Modificarjbtn;
    private javax.swing.JButton Postresjbtn;
    private javax.swing.JButton Refrescarjbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
