/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_estructuras_final.interfaz;

import proyecto_estructuras_final.logica.Control;

/**
 *
 * @author 50688
 */
public class Usuario extends javax.swing.JFrame {

    /**
     *
     */
    
    Control myControl;
    public Usuario(Control myControl) {
        initComponents();
        this.setTitle("Bienvenido Usuario");
        this.setLocationRelativeTo(null);
        val1.setVisible(false);
        val2.setVisible(false);
        valtodos.setVisible(false);
        this.myControl = myControl;
    }
    int cont = 0;

    public void validar(String nombre, String cedula) {
        if (nombre.equals("")) {
            val1.setVisible(true);
            valtodos.setVisible(true);
            cont++;
        } else {
            val1.setVisible(false);
            valtodos.setVisible(false);
        }
        if (cedula.equals("")) {
            val2.setVisible(true);
            valtodos.setVisible(true);
            cont++;
        } else {
            val2.setVisible(false);
            valtodos.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        Continuejbt = new javax.swing.JButton();
        NombreUsuarioL = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JTextField();
        CédulaLabel = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        val2 = new javax.swing.JLabel();
        valtodos = new javax.swing.JLabel();
        val1 = new javax.swing.JLabel();
        CédulaUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, 40));

        Continuejbt.setText("Aceptar");
        Continuejbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuejbtActionPerformed(evt);
            }
        });
        getContentPane().add(Continuejbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 110, 40));

        NombreUsuarioL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NombreUsuarioL.setForeground(new java.awt.Color(255, 255, 255));
        NombreUsuarioL.setText("Nombre Completo: ");
        getContentPane().add(NombreUsuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        NombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 150, -1));

        CédulaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        CédulaLabel.setForeground(new java.awt.Color(255, 255, 255));
        CédulaLabel.setText("Cédula:");
        getContentPane().add(CédulaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        Title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Por favor, ingrese sus datos personales");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 500, 90));

        val2.setForeground(new java.awt.Color(255, 51, 0));
        val2.setText("Cédula Incorrecta");
        getContentPane().add(val2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        valtodos.setForeground(new java.awt.Color(255, 255, 255));
        valtodos.setText("Requerido");
        getContentPane().add(valtodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        val1.setForeground(new java.awt.Color(255, 51, 0));
        val1.setText("Nombre incorrecto");
        getContentPane().add(val1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        CédulaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CédulaUsuarioActionPerformed(evt);
            }
        });
        CédulaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CédulaUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(CédulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_estructuras_final/Imagenes/danke menu.jpg"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        Inicio in = new Inicio(this.myControl);
        in.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void ContinuejbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuejbtActionPerformed
        // TODO add your handling code here:

        cont = 0;
        validar(NombreUsuario.getText(), CédulaUsuario.getText());
        if (cont == 0) {
            TomarPedido tomar = new TomarPedido(this.myControl);
            tomar.setLocationRelativeTo(null);
            tomar.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_ContinuejbtActionPerformed

    private void CédulaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CédulaUsuarioActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_CédulaUsuarioActionPerformed

    private void CédulaUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CédulaUsuarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_CédulaUsuarioKeyTyped

    private void NombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreUsuarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
    }//GEN-LAST:event_NombreUsuarioKeyTyped

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Control myControl = new Control ();
                new Usuario(myControl).setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton Continuejbt;
    private javax.swing.JLabel CédulaLabel;
    private javax.swing.JTextField CédulaUsuario;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JLabel NombreUsuarioL;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel val1;
    private javax.swing.JLabel val2;
    private javax.swing.JLabel valtodos;
    // End of variables declaration//GEN-END:variables
}
